### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by pi0** [nuxt-modules/ngrok#1]
First of all nice work on module 💯 

- [x] - I think worth mentioning about `NGROK_TOKEN` in docs
- [x] - Why we need adding to `runtimeConfig.url`? Anyway if necessary, we should keep it namespaced (`$config.ngrok.url`)
- [x] - chalk dependency is missing in package.json
- [x] - package.json lacks description (and probably `ngrok` tag)
- [x] - We may need to set version +1 major than current published package (2.0.0)
- [x] - It would be nice putting a link to packages we use in wrapper modules (https://github.com/bubenshchykov/ngrok) with a comment in top

**Comment by pi0** [comment]
Also after publish would be nice opening a PR in nuxt-community/modules to update link and remove source of old package

**Comment by debs-obrien** [comment]
This is not necessary and can be removed. It is only incase we want to show it in the browser in the page in the /example in the module but I think it is enough in the cli.

**Comment by debs-obrien** [comment]
if we replace the other module are there anything that we need to think about that was in the other module, other options etc @pi0 ?

**Comment by pi0** [comment]
> This is not necessary and can be removed. It is only incase we want to show it in the browser in the page in the /example in the module but I think it is enough in the cli.

- [x] I toguht same. Still was a nice idea. We just need namespacing config since if one-day nuxt adds `url` it will be conflicting with one from ngrok

> if we replace the other module are there anything that we need to think about that was in the other module, other options etc @pi0 ?

- [ ] Actually there are plenty of useful option we can keep supporting: https://github.com/nuxt-community/modules/tree/master/packages/ngrok (simply passing options to original `ngrok` module. We just need docs and sanity defaults)

- [ ] Also default `process.env.npm_package_name` as addr makes module to use name of package as ngrok subdomain (if possible)

**Comment by debs-obrien** [comment]
@pi0 - It would be nice putting a link to packages we use in wrapper modules (https://github.com/bubenshchykov/ngrok) with a comment in top.
Where exactly? I have it mentioned in the docs but would you also like it in the module code?

**Comment by debs-obrien** [comment]
@pi0  how can I test these out:
Actually there are plenty of useful option we can keep supporting: https://github.com/nuxt-community/modules/tree/master/packages/ngrok (simply passing options to original ngrok module. We just need docs and sanity defaults)

I tried adding them to the example but don't understand how to get them to work. I need simple examples to understand. like what value to I add to get subdomain or default value for addr?
https://ngrok.com/docs#config

**Comment by pi0** [comment]
Actually options are defined here: https://www.npmjs.com/package/ngrok#options (we should pass them to `ngrok.connect` instead of only port)

Old module has it implemented: https://github.com/nuxt-community/modules/blob/master/packages/ngrok/index.js#L31 (with new template we need to set in DEFAULTS)

Also for comment see line #11

**Comment by debs-obrien** [comment]
ok @pi0  link added. I am not sure I understand how to add the other options. I have added them to the ModuleOptions object but from there not sure how to use them or make sure they can be used

**Comment by debs-obrien** [comment]
options added during pair programming: https://github.com/debs-obrien/ngrok/commit/70c85a35b96d63f466fa1c073feb908563cbdaf3

**Comment by debs-obrien** [comment]
docs finished
